### PR TITLE
Final Version of DepressiLess

### PR DESCRIPTION
**Pull request by marilenaManoli**
It won't let me automatically merge my latest version of DepressiLess, not sure how. But I will still create this PR to ensure the code is on main if it doesnt cause any important issues.

### CODE REVIEW

**Comment by ArchieUni** [comment]
@marilenaManoli It's because your branch is behind main and has conflicts, you need to merge an up to date version of main into your branch locally first. Once the conflicts have been resolved drop me a message and I will help you sort out the CI checks!

**Comment by marilenaManoli** [comment]
I tried merging but I got this error: git pull origin main

remote: Enumerating objects: 11247, done.
remote: Counting objects: 100% (409/409), done.
remote: Compressing objects: 100% (211/211), done.
remote: Total 11247 (delta 324), reused 216 (delta 198), pack-reused 10838
Receiving objects: 100% (11247/11247), 341.46 MiB | 6.99 MiB/s, done.
Resolving deltas: 100% (3925/3925), completed with 45 local objects.
fatal: bad object refs/stash 2
error: https://github.com/Archie-Adams/larks.git did not send all necessary objects

Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log
Automatic cleanup will not be performed until the file is removed.

fatal: bad object refs/stash 2
fatal: failed to run repack

I tried removing object refs/stash which was done successfully but it gave me the same result

**Comment by marilenaManoli** [comment]
> I tried merging but I got this error: git pull origin main
> 
> remote: Enumerating objects: 11247, done. remote: Counting objects: 100% (409/409), done. remote: Compressing objects: 100% (211/211), done. remote: Total 11247 (delta 324), reused 216 (delta 198), pack-reused 10838 Receiving objects: 100% (11247/11247), 341.46 MiB | 6.99 MiB/s, done. Resolving deltas: 100% (3925/3925), completed with 45 local objects. fatal: bad object refs/stash 2 error: https://github.com/Archie-Adams/larks.git did not send all necessary objects
> 
> Auto packing the repository in background for optimum performance. See "git help gc" for manual housekeeping. warning: The last gc run reported the following. Please correct the root cause and remove .git/gc.log Automatic cleanup will not be performed until the file is removed.
> 
> fatal: bad object refs/stash 2 fatal: failed to run repack
> 
> I tried removing object refs/stash which was done successfully but it gave me the same result

@Archie-Adams

**Comment by ArchieUni** [comment]
@marilenaManoli did you remove the `.git/gc.log` file and then pull again?

**Pull request merged**
